// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdIFvpmDtGwDB-2qAs99Dd5ELTIX0EGws',
    appId: '1:626864770589:web:ecd0919a507996276b80f4',
    messagingSenderId: '626864770589',
    projectId: 'minichat-5fef6',
    authDomain: 'minichat-5fef6.firebaseapp.com',
    storageBucket: 'minichat-5fef6.firebasestorage.app',
    measurementId: 'G-06VQH582JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ASrS60eclBZJa11LNDADKzaGH8mMb5A',
    appId: '1:626864770589:android:7ceec97f224c2bea6b80f4',
    messagingSenderId: '626864770589',
    projectId: 'minichat-5fef6',
    storageBucket: 'minichat-5fef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMxp7Ix7YlU-Bb0CiOjFJv2w4w-zq4-R4',
    appId: '1:626864770589:ios:6893a58e1ccb4a276b80f4',
    messagingSenderId: '626864770589',
    projectId: 'minichat-5fef6',
    storageBucket: 'minichat-5fef6.firebasestorage.app',
    iosBundleId: 'com.example.chat1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMxp7Ix7YlU-Bb0CiOjFJv2w4w-zq4-R4',
    appId: '1:626864770589:ios:6893a58e1ccb4a276b80f4',
    messagingSenderId: '626864770589',
    projectId: 'minichat-5fef6',
    storageBucket: 'minichat-5fef6.firebasestorage.app',
    iosBundleId: 'com.example.chat1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdIFvpmDtGwDB-2qAs99Dd5ELTIX0EGws',
    appId: '1:626864770589:web:8b7f155b6bd1f4c26b80f4',
    messagingSenderId: '626864770589',
    projectId: 'minichat-5fef6',
    authDomain: 'minichat-5fef6.firebaseapp.com',
    storageBucket: 'minichat-5fef6.firebasestorage.app',
    measurementId: 'G-QP4W1VHPE4',
  );
}
